version: "3.8"
services:
  etuutt:
    image: larueli/php-base-image:7.1
    ports:
    - 8000:8080
    user: "${UID}:0"
    volumes:
    - .:/var/www/html:rw
    depends_on:
      - db
    env_file:
      - .env.local

  db:
    image: mariadb
    env_file:
      - .env.local
    volumes:
      - db:/var/lib/mysql

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
    - 8080:8080

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  db:

###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
