
parameters:

services:

    # Forms
    etu.covoit.form.proposal:
        class: Etu\Module\CovoitBundle\Form\CovoitType

    etu.covoit.form.message:
        class: Etu\Module\CovoitBundle\Form\CovoitMessageType

    etu.covoit.form.search:
        class: Etu\Module\CovoitBundle\Form\SearchType

    etu.covoit.form.alert:
        class: Etu\Module\CovoitBundle\Form\CovoitAlertType

    # Searh query mapper
    etu.covoit.query_mapper.search:
        class: Etu\Module\CovoitBundle\QueryMapper\SearchMapper

    # Notifications dispatcher
    etu.covoit.notifs_dispatcher:
        class: Etu\Module\CovoitBundle\Alerts\NotificationsDispatcher
        arguments: ["@doctrine", "@etu.notifs.sender"]

    # Notifications helper
    etu.covoit.notifs.new_message:
        class: Etu\Module\CovoitBundle\Notification\Helper\NewMessageHelper
        arguments: ["@twig"]
        tags:
            - { name: etu.notifs_helper }

    etu.covoit.notifs.edited:
        class: Etu\Module\CovoitBundle\Notification\Helper\EditedHelper
        arguments: ["@twig"]
        tags:
            - { name: etu.notifs_helper }

    etu.covoit.notifs.canceled:
        class: Etu\Module\CovoitBundle\Notification\Helper\CanceledHelper
        arguments: ["@twig"]
        tags:
            - { name: etu.notifs_helper }

    etu.covoit.notifs.alert:
        class: Etu\Module\CovoitBundle\Notification\Helper\AlertHelper
        arguments: ["@twig"]
        tags:
            - { name: etu.notifs_helper }

    etu.covoit.notifs.subscription:
        class: Etu\Module\CovoitBundle\Notification\Helper\SubscriptionHelper
        arguments: ["@twig"]
        tags:
            - { name: etu.notifs_helper }
