
parameters:

services:

    # Twig permissions checker extension
    etu.forum.twig.permissions:
        class: Etu\Module\ForumBundle\Twig\Extension\PermissionsExtension
        tags:
            - { name: twig.extension }
    etu.forum.twig.number:
        class: Etu\Module\ForumBundle\Twig\Extension\NumberExtension
        tags:
            - { name: twig.extension }
    etu.notifs.thread_created:
        class: Etu\Module\ForumBundle\Notification\Helper\ThreadCreatedHelper
        arguments: ["@twig"]
        tags:
            - { name: etu.notifs_helper }
    etu.notifs.thread_answered:
        class: Etu\Module\ForumBundle\Notification\Helper\ThreadAnsweredHelper
        arguments: ["@twig"]
        tags:
            - { name: etu.notifs_helper }
