imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver:   pdo_sqlite
        host:     ~
        port:     ~
        dbname:   ~
        user:     "%database_user%"
        password: "%database_password%"
        path:     "%kernel.root_dir%/../var/tests.db"
        charset:  UTF8
