
parameters:

services:

    # Notifications helper
    etu.notifs.orga_message:
        class: Etu\Module\AssosBundle\Notification\Helper\OrgaMessageHelper
        arguments: ["@twig"]
        tags:
            - { name: etu.notifs_helper }
