
parameters:

services:

    events_repository:
        class:           Doctrine\ORM\EntityRepository
        factory:         ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:       ['EtuModuleEventsBundle:Event']
        tags:
            - { name: calendr.event_provider }


    # Notifications helper
    etu.notifs.event_created_all:
        class: Etu\Module\EventsBundle\Notification\Helper\EventCreatedAllHelper
        arguments: ["@twig"]
        tags:
            - { name: etu.notifs_helper }

    etu.notifs.event_created_category:
        class: Etu\Module\EventsBundle\Notification\Helper\EventCreatedCategoryHelper
        arguments: ["@twig"]
        tags:
            - { name: etu.notifs_helper }

    etu.notifs.event_edited:
        class: Etu\Module\EventsBundle\Notification\Helper\EventEditedHelper
        arguments: ["@twig"]
        tags:
            - { name: etu.notifs_helper }

    etu.notifs.event_deleted:
        class: Etu\Module\EventsBundle\Notification\Helper\EventDeletedHelper
        arguments: ["@twig"]
        tags:
            - { name: etu.notifs_helper }
