<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\WebServerBundle\WebServerBundle::class => ['dev' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Artgris\Bundle\FileManagerBundle\ArtgrisFileManagerBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['all' => true],
    FrequenceWeb\Bundle\CalendRBundle\FrequenceWebCalendRBundle::class => ['all' => true],
    FOS\JsRoutingBundle\FOSJsRoutingBundle::class => ['all' => true],
    Knp\Bundle\PaginatorBundle\KnpPaginatorBundle::class => ['all' => true],
    Knp\Bundle\TimeBundle\KnpTimeBundle::class => ['all' => true],
    Liip\ImagineBundle\LiipImagineBundle::class => ['all' => true],
    Nelmio\ApiDocBundle\NelmioApiDocBundle::class => ['all' => true],
    Nelmio\CorsBundle\NelmioCorsBundle::class => ['all' => true],
    Sensio\Bundle\DistributionBundle\SensioDistributionBundle::class => ['all' => true],
    Sentry\SentryBundle\SentryBundle::class => ['all' => true],
    EightPoints\Bundle\GuzzleBundle\EightPointsGuzzleBundle::class => ['all' => true],
    Sonata\IntlBundle\SonataIntlBundle::class => ['all' => true],
    Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle::class => ['all' => true],
    Symfony\Bundle\AsseticBundle\AsseticBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],

    //Etu Core
    Etu\Core\CoreBundle\EtuCoreBundle::class => ['all'=>true],
    Etu\Core\UserBundle\EtuUserBundle::class => ['all'=>true],
    Etu\Core\ApiBundle\EtuCoreApiBundle::class => ['all'=>true],

    //EtuUTT plugins
    Etu\Module\ArgentiqueBundle\EtuModuleArgentiqueBundle::class => ['all'=>true],
    Etu\Module\AssosBundle\EtuModuleAssosBundle::class => ['all'=>true],
    Etu\Module\BugsBundle\EtuModuleBugsBundle::class => ['all'=>true],
    Etu\Module\CumulBundle\EtuModuleCumulBundle::class => ['all'=>true],
    Etu\Module\CovoitBundle\EtuModuleCovoitBundle::class => ['all'=>true],
    Etu\Module\DaymailBundle\EtuModuleDaymailBundle::class => ['all'=>true],
    Etu\Module\EventsBundle\EtuModuleEventsBundle::class => ['all'=>true],
    Etu\Module\ForumBundle\EtuModuleForumBundle::class => ['all'=>true],
    Etu\Module\TrombiBundle\EtuModuleTrombiBundle::class => ['all'=>true],
    Etu\Module\TVBundle\EtuModuleTVBundle::class => ['all'=>true],
    Etu\Module\UVBundle\EtuModuleUVBundle::class => ['all'=>true],
    Etu\Module\WikiBundle\EtuModuleWikiBundle::class => ['all'=>true],
    Etu\Module\UploadBundle\EtuModuleUploadBundle::class => ['all'=>true],
    Etu\Module\SIABundle\EtuModuleSIABundle::class => ['all'=>true],
    Etu\Module\BadgesBundle\EtuModuleBadgesBundle::class => ['all'=>true],
];
