
parameters:

services:

    # Notifications helper
    etu.notifs.uv_new_comment:
        class: Etu\Module\UVBundle\Notification\Helper\NewCommentHelper
        arguments: ["@twig"]
        tags:
            - { name: etu.notifs_helper }
    etu.notifs.uv_new_review:
        class: Etu\Module\UVBundle\Notification\Helper\NewReviewHelper
        arguments: ["@twig"]
        tags:
            - { name: etu.notifs_helper }
