
parameters:

services:
    argentique.url_builder:
        class: Etu\Module\ArgentiqueBundle\Glide\UrlBuilder
        arguments: [ "%secret%", "@service_container" ]

    argentique.twig.url_builder_extension:
        class: Etu\Module\ArgentiqueBundle\Twig\UrlBuilderExtension
        arguments: [ "@argentique.url_builder" ]
        tags:
            - { name: twig.extension }

    argentique.SessionUpdater:
        class: Etu\Module\ArgentiqueBundle\EventListener\SessionUpdater
        arguments: ["@security.authorization_checker", "@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.response }

    argentique.filemanagerconfig:
        class: Etu\Module\ArgentiqueBundle\FileManager\FileManagerConf
        arguments: ["@security.authorization_checker"]
