
parameters:

services:

    # Notifications helper
    etu.notifs.bugs_new_comment:
        class: Etu\Module\BugsBundle\Notification\Helper\NewCommentHelper
        arguments: ["@twig"]
        tags:
            - { name: etu.notifs_helper }

    etu.notifs.bugs_new_opened:
        class: Etu\Module\BugsBundle\Notification\Helper\NewOpenedHelper
        arguments: ["@twig"]
        tags:
            - { name: etu.notifs_helper }

    etu.notifs.bugs_closed:
        class: Etu\Module\BugsBundle\Notification\Helper\BugClosedHelper
        arguments: ["@twig"]
        tags:
            - { name: etu.notifs_helper }
